# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support 
# documentation.

name: Dart

on:
  push:
    branches: [ "dev" ]

jobs: 
  windows:
    runs-on: windows-latest
    outputs:
      next1: ${{ steps.version.outputs.next }}
      next2: ${{ steps.version2.outputs.value }}

    steps:
      - uses: actions/checkout@v3
   
      - uses: PssbleTrngle/VersionManagment@v2
        id: version
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fallback: "${{github.ref_name}}-0.2.0"
          prefix: "${{github.ref_name}}-"
         
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.next }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.type }}
          
      - uses: mad9000/actions-find-and-replace-string@3
        id: version2
        with:
          source: ${{ steps.version.outputs.next }} # this translates to ref/heads/main on the main branch, but can be any arbitrary string 
          find: '${{github.ref_name}}-'        # we want to remove ref/heads/ from source 
          replace: ''               # and replace it with a blank string (ie. removing it)  
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version
      - name: Install project dependencies
        working-directory: ./src/desk/test_app
        run: flutter pub get
      - name: Enable windows build
        working-directory: ./src/desk/test_app
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        working-directory: ./src/desk/test_app
        run: flutter build windows --release --build-name ${{steps.version2.outputs.value}} --build-number ${{github.run_number}}
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{steps.version.outputs.next}}-windows.zip
          directory: ./src/desk/test_app/build/windows/runner/Release   
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src/desk/test_app/build/windows/runner/Release/${{steps.version.outputs.next}}-windows.zip
          asset_name: ${{steps.version.outputs.next}}-windows.zip
          tag:  ${{ steps.version.outputs.next  }}
          overwrite: true
          body: "This is my release text" 
          
  linux:
    runs-on: ubuntu-latest
    needs: windows 
    steps:
      - env:
          next1: ${{needs.windows.outputs.next1}}
          next2: ${{needs.windows.outputs.next2}}
      - uses: actions/checkout@v3
   
     
      - name: Use the version
        run: |
          echo "$next1 $next2"

     
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version
      - name: Install project dependencies
        working-directory: ./src/desk/test_app
        run: flutter pub get
      - name: Enable windows build
        working-directory: ./src/desk/test_app
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        working-directory: ./src/desk/test_app
        run: flutter build apk --no-tree-shake-icons --release --build-name ${{next2}} --build-number ${{github.run_number}}
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src/desk/test_app/build/app/outputs/flutter-apk/app-release.apk
          asset_name: ${{steps.version.outputs.next}}-apk.apk
          tag:  ${{ steps.version.outputs.next  }}
          overwrite: true
          body: "${{ steps.version.outputs.next  }} Developer version" 
