# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
   
      - uses: PssbleTrngle/VersionManagment@v2
        id: version
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fallback: "${{github.ref_name}}-0.2.0"
          prefix: "${{github.ref_name}}-"
         
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.next }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.type }}

   
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src/desk/test_app/linux/main.cc
          asset_name: linux.cc
          tag:  ${{ steps.version.outputs.next  }}
          overwrite: true
          body: "This is my release text"
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src/desk/test_app/windows/CMakeLists.txt
          asset_name: Windows.cc
          tag:  ${{ steps.version.outputs.next  }}
          overwrite: true
          body: "This is my release text1"
